### PR TITLE
First pull request

### PR DESCRIPTION
**Pull request by r4phab**
Hi Boris, I'm requesting my first pull before adding the other ECAB subtests. Theses changes are code refactoring and adding ECAB subtests switches.

### CODE REVIEW

**Comment by borisyurkevich** [comment]
Oh hi, I will review this later, looks good so far. 👍🏻

**Comment by borisyurkevich** [comment]
Hi again @r4phab. I wasn't able to build your branch because of the `ld: framework not found Slt` error. Please provide with instructions how to add it to the project or include into git.

**Comment by borisyurkevich** [comment]
Because this work I did is for my clients even if conflict resolved I can't guarantee to accept this pull request. I need to speak to them first. I can see you are doing speech recognition and they will be defiantly interested in this.

**Comment by borisyurkevich** [comment]
I would like to do a merge, just help me to build your branch.

**Comment by r4phab** [comment]
Hello @borisyurkevich ,

Yeah sorry I’m currently working on the speech recognition right now. I had no idea the pull request would request the latest changes instead of the changes at the time of the request. 

Don’t merge right now because everything is not working at the time. I’ll come to you later (probably this week end) when my changes are good and tested. 

I'm doing this project for Oliver and Jan for my dissertation like you have done last year.

**Comment by borisyurkevich** [comment]
Okay, nice to meet you. This is my first pull request from other side, so bare with me. Yes, you a right. You don't need latest changes, keep working and take your time. I will help with the merge.

**Comment by borisyurkevich** [comment]
We need to resolve is the merge conflict. I will appreciate if you keep your branch up to date. I am not able to resolve this correctly because I can't clearly separate my old code from `iOS9` to the new code in `iOS9` and your new changes.

**Comment by borisyurkevich** [comment]
Also, I found several Core Data warnings. Some of them for the current revision and some of them for the version 2 which is odd, we shouldn't modify old version. You need to be very careful with this, any change to Core Data will crash Oliver's iPad when he will update.

If you want to make changes to Core Data and preserve backward compatibilty, perform lightweight data migration, this requires creating new version first, and then modifying only new version.

**Comment by r4phab** [comment]
I can help with the merge of course.

Yes I didn’t know about core data before starting the project, that is why I may have edited some previous versions..

**Comment by r4phab** [comment]
I may be able to help for the merge but I can't because of permission issues. Indeed, I don't have write access so I can't even see any merge conflicts :/

**Comment by borisyurkevich** [comment]
You don't need write access. You already cloned this repository. Just pull the today's latest changes in and make new pull request.

**Pull request merged**
